---
kind: Template
apiVersion: v1
labels:
  app: "${NAME}"
  build: "${NAME}"
  template: "${NAME}-bc-template"
metadata:
  name: N8N
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${NAME}"
    spec:
      lookupPolicy:
        local: false
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${NAME}"
      labels:
        buildconfig: "${NAME}"
    spec:
      completionDeadlineSeconds: 600
      failedBuildsHistoryLimit: 3
      successfulBuildsHistoryLimit: 3
      output:
        to:
          kind: ImageStreamTag
          name: "${NAME}:${VERSION}"
      postCommit: {}
      resources:
        limits:
          cpu: 2000m
          memory: 2Gi
        requests:
          cpu: 1000m
          memory: 1Gi
      runPolicy: SerialLatestOnly
      source:
        dockerfile: |
          FROM BuildConfig
        type: Dockerfile
      strategy:
        dockerStrategy:
          buildArgs:
            - name: N8N_VERSION
              value: "${N8N_VERSION}"
          from:
            kind: DockerImage
            name: image-registry.openshift-image-registry.svc:5000/af2668-tools/node:14.15-alpine
        type: Docker
      triggers:
        - type: ConfigChange
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.
    required: true
    value: n8n
  - name: N8N_VERSION
    displayName: n8n Version
    description: Version of n8n to use
    required: true
    value: 0.36.1
  - name: VERSION
    displayName: Image version tag
    description: The version tag of the built image
    required: true
    value: latest
